trigger:
  branches:
    include:
      - dev
      - hml
      - master
      - main
  paths:
    include:
      - frontend/**
      - azure-pipelines-frontend.yml

pool:
  name: Naos

variables:
  repositoryName: "monitoramento-pdvs-frontend"
  VITE_API_URL: "https://api-monitoramento-pdvs.lojasrede.com.br"

steps:
  - task: Docker@2
    displayName: "Docker Login"
    inputs:
      command: login
      containerRegistry: "Nexus 3"

  - bash: |
      echo "VITE_API_URL=$(VITE_API_URL)" > frontend/.env.production
    displayName: "Configurar URL do backend"

  - task: Docker@2
    displayName: "Build & Push imagem Docker Frontend"
    inputs:
      command: buildAndPush
      containerRegistry: "Nexus 3"
      repository: "$(repositoryName)"
      dockerfile: "frontend/Dockerfile"
      buildContext: "frontend"
      tags: |
        $(Build.BuildNumber)
        latest

  - bash: |
      echo "$(Build.BuildNumber)" > $(Build.ArtifactStagingDirectory)/image-tag.txt
    displayName: "Gerar arquivo image-tag.txt"

  - task: PublishBuildArtifacts@1
    displayName: "Publicar Artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
